[package]
name = "human_use_of_human_beings"
version = "0.1.0"
authors = ["Andrew C. Smith <andrewchristophersmith@gmail.com>"]

[dependencies]
voting_experts = { path = "../voting_experts" }
radix_trie = "0.1.3"
serde = "1.0"
serde_json = "1.0"
bincode = "1.0"
